kind: Deployment
apiVersion: apps/v1
metadata:
  name: sendtemplatemail
  namespace: camunda-workers
  labels:
    app: digit-plattform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sendtemplatemail
  template:
    metadata:
      labels:
        app: sendtemplatemail
        app.kubernetes.io/name: sendtemplatemail
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
        - name: sendtemplatemail
          image: ghcr.io/haninge-digit/digit-worker-sendtemplatemail:latest   # Set tag to "lab" for lab versions and "latest" for production versions
          imagePullPolicy: Always
          env:
            - name: DEBUG
              value: 'false'  # Change to 'true' for debugging
            - name: ZEEBE_ADDRESS
              value: camunda-zeebe-gateway.camunda-zeebe:26500
            - name: AD_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: ms365mail-secret
                  key: AD_TENANT_ID
            - name: AD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ms365mail-secret
                  key: AD_CLIENT_ID
            - name: AD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ms365mail-secret
                  key: AD_CLIENT_SECRET
            - name: TEMPLATE_URL
              valueFrom:
                configMapKeyRef:
                  name: sendtemplatemail-config
                  key: TEMPLATE_URL
          resources:    # Might need to be tailored
            limits:
              memory: "128Mi"
              cpu: "100m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext: {}
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
