apiVersion: v1
kind: Secret
metadata:
  name: sendtemplatemail-secret
  namespace: camunda-workers
data:
  AD_CLIENT_ID: <client_id>          # echo -n <client_id> | base64
  AD_CLIENT_SECRET: <client_secret>  # echo -n <client_secret> | base64
